/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubtitlesList: typeof import('./components/SubtitlesList.vue')['default']
    SubtitlesTimeline: typeof import('./components/SubtitlesTimeline.vue')['default']
    SubtitleTimeline: typeof import('./components/SubtitleTimeline.vue')['default']
    UploadFile: typeof import('./components/UploadFile.vue')['default']
    VideoPlayer: typeof import('./components/VideoPlayer.vue')['default']
  }
}
